version: '3.8'

services:
  vger-server1:
    build:
      args:
        #just to mock prod, you can change dokerdfile to build the CI implementation
        REPOGH: https://github.com/pabloped/vger.testsite.prod
        FOLDERDOCS: prod  
    environment:
      - LSTPORT=8081
      - LSTHOST=vger-server1  
    extends:
      file: docker-compose.base.yml
      service: debian-server1
    image: vger-serv1
    depends_on:
      - vger-rep

    #doesnt expose the port in prod
    #ports:
    #  - 8081:8081

  #clone for redundancy
  vger-server2:
    build:
      args:
        REPOGH: https://github.com/pabloped/vger.testsite.prod
        FOLDERDOCS: prod
    environment:
      - LSTPORT=8082
      - LSTHOST=vger-server2  
    extends:
      file: docker-compose.base.yml
      service: debian-server1
    image: vger-serv2
    depends_on:
      - vger-rep

    #ports:
    #  - 8082:8082

  #clone for redundancy
  vger-server3:
    build:
      args:
        REPOGH: https://github.com/pabloped/vger.testsite.prod
        FOLDERDOCS: prod  
    environment:
      - LSTPORT=8083
      - LSTHOST=vger-server3  
    extends:
      file: docker-compose.base.yml
      service: debian-server1
    image: vger-serv3
    depends_on:
      - vger-rep

    #ports:
    #  - 8083:8083


  vger-rep:
    extends:
      file: docker-compose.base.yml
      service: debian-rep
    ports:
      - 80:80
      